services:
  - type: web
    name: task-api
    env: node
    plan: free
    buildCommand: npm ci && npm run build:render
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
